# -*- encoding: utf-8 -*-
{
    'name': 'Nibbana',
    'version': '11.0.1.0.7',
    'author': 'Odooist',
    'maintainer': 'Odooist',
    'support': 'odooist@gmail.com',
    'license': 'OPL-1',
    'category': 'Project',
    'summary': 'Personal project and task management system based on GTD concept',
    'description': """Nibbana base module""",
    'depends': [
        'web',
        'mail',
        'board',
        'web_tour',
        ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/assets.xml',
        'views/views.xml',
        'views/inbox.xml',
        'views/area.xml',
        'views/context.xml',
        'views/project.xml',
        'views/project_inactive.xml',
        'views/task.xml',
        'views/reference.xml',
        'views/metric.xml',
        'views/act.xml',
        'views/act_distinct.xml',
        'views/timeline.xml',
        'views/about.xml',
        'views/settings.xml',
        'views/templates.xml',
        'views/ir_cron.xml',
        ],
    'demo': [
        'demo/area.xml',
        'demo/context.xml',
        'demo/project.xml',
        ],
    "qweb": [
        "static/src/xml/*.xml",
    ],    
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': [
        'static/description/projects_screenshot.png', 
        'static/description/tasks.png', 
        'static/description/areas_and_wheel.png', 
        'static/description/metrics.png', 
    ],
}
